# version: '3.4'

# services:
#   jiraclone.api:
#     environment:
#       - ASPNETCORE_ENVIRONMENT=Development
#       - ASPNETCORE_HTTP_PORTS=5000
#       - ASPNETCORE_HTTPS_PORTS=5001
#     ports:
#       - "5000:5000"
#       - "5001:5001"
#     volumes:
#       - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
#       - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro


version: '3.4'

services:
  jiraclone.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Npgsql=Host=jiraClone.database;Port=5432;Database=jiraClone;Username=postgres;Password=postgres
    build:
      context: .
      dockerfile: JiraClone.API/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    depends_on:
      - jiraClone.database
    networks:
      - app_network
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
networks:
  app_network:
    driver: bridge